spring.application.name: applications

server.port: ${APPLICATIONS_SERVICE_PORT}

spring.zipkin.locator.discovery.enabled: true
management.server.port: ${APPLICATIONS_SERVICE_MANAGEMENT_PORT}
management.security.enabled: false

management:
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info.app.name: Сервис работы с обращениями заявителей (прототип)
info.app.description: Сервис работы с обращениями заявителей (прототип)
info.app.version: 1.0.0

management.health.binders.enabled: true

eureka:
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl.defaultZone: ${EUREKA_DEFAULT_ZONE_URL}
    healthcheck.enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /health
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      management:
        port: ${management.server.port}
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        context-path: /

spring:
  cloud:
    inetutils:
      preferred-networks:
        - 10.0

spring.boot.admin:
  client:
    url: ${ADMIN_URL}
    period: 10000
    instance:
      prefer-ip: true
#      name: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#      service-base-url: http://${spring.application.name}:${server.port}

# Настройки Cloud Stream для Kafka Streams
spring.cloud.stream.kafka.binder:
  brokers: ${KAFKA_BOOTSTRAP_SERVERS}
  autoAddPartitions: true
  replicationFactor: 2
  minPartitionCount: 2

spring.cloud.stream.kafka.streams:
  binder:
    brokers: ${KAFKA_BOOTSTRAP_SERVERS}
    zkNodes: ${KAFKA_ZK_NODES}
    serde-error: logandcontinue
    configuration:
      application.server: localhost:${APPLICATIONS_SERVICE_PORT}
      commit.interval.ms: 200
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      auto.register.schemas: true
      specific.avro.reader: true
      max.schemas.per.subject: 1000
      state.dir: ${KAFKA_STATE_DIR:/tmp/kafka-state}
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
      default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
  bindings:
    events-outgoing.producer:
      applicationId: ${spring.application.name}-stream
    events-incoming.consumer:
      applicationId: ${spring.application.name}-stream
      keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
      valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    events-projecting-outgoing.producer:
      applicationId: ${spring.application.name}-projector
      keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
      valueSerde: test.common.service.EventHolderSerde
    events-projecting-incoming.consumer:
      applicationId: ${spring.application.name}-projector
      keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
      valueSerde: test.common.service.EventHolderSerde

spring.cloud.stream.bindings:
  events-incoming:
    destination: ${EVENTS_TOPIC_NAME}
    group: ${spring.application.name}
    consumer:
      concurrency: 3
      partitioned: true
      useNativeDecoding: true
  events-outgoing:
    destination: ${EVENTS_TOPIC_NAME}
    producer:
      partition-count: 5
      partition-key-expression: headers['kafka_messageKey']
      useNativeEncoding: true
  events-projecting-incoming:
    destination: ${SNAPSHOT_TOPIC_NAME}
    group: ${spring.application.name}
    consumer:
      useNativeDecoding: true
  events-projecting-outgoing:
    destination: ${SNAPSHOT_TOPIC_NAME}
    producer:
      useNativeEncoding: true
  events-quarantine-outgoing:
    destination: events-quarantine
    producer:
      useNativeEncoding: true

spring.cloud.stream.kafka.bindings:
  events-outgoing.producer:
    bufferSize: 0
    batchTimeout: 200
    configuration:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      commit.interval.ms: 200
      batch.size: 0
      retention.ms: -1
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      auto.register.schemas: true
      specific.avro.reader: true
      max.schemas.per.subject: 1000
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
      default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
  events-projecting-outgoing.producer:
    bufferSize: 0
    batchTimeout: 200
    configuration:
      commit.interval.ms: 200
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
  events-incoming.consumer:
    autoRebalanceEnabled: true
    configuration:
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
  events-projecting-incoming.consumer:
    autoRebalanceEnabled: true
    configuration:
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor

spring.cloud.stream.schemaRegistryClient.endpoint: ${KAFKA_SCHEMA_REGISTRY}

# Специфичные настройки приложения

kite.eventstore:
  kafka:
    stateStorePath: /event.stream
    localStore.name: ${STATE_STORE_NAME}
  mongo:
    dbAddress: mongodb://${MONGO_SERVER}
    database.name: ${MONGO_EVENTS_DB}
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}
    authenticationDb: ${MONGO_AUTH_DB}


kite.rest.regulations.service.name: regulations
kite.rest.documents.service.name: document-types

#rest.documents.service.name: documents-service

applications.published.datasource:
  driverClassName: org.postgresql.Driver
  jdbc-url: jdbc:postgresql://${POSTGRES_SERVER}/requests
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  type: com.zaxxer.hikari.HikariDataSource
  pool-name: ${spring.application.name}
  maximum-pool-size: ${POSTGRES_MAX_POOL_SIZE:10}
  max-lifetime: ${POSTGRES_CONNECTION_LIFETIME:10000}
  minimum-idle: 1


#spring.aop.proxy-target-class: true